version: "3.9"

services:
  chroma:
    image: chromadb/chroma:1.3.5
    container_name: chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
    ports:
      - "8000:8000"
    volumes:
      # НЕ /chroma/chroma черт возьми!
      # from task6
      - ./chroma_db:/data
    networks:
      - rag-app-net

  rag-kb-updater:
    build: ./rag_kb_updater
    container_name: rag-kb-updater
    env_file:
      - ./rag_kb_updater/.env
    depends_on:
      - chroma
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      # нужно для PERSISTENT клиента (но rag-api-safe и rag-kb-updater не смогут работать вместе)
      # в docker только для подсчета размера
      - ./chroma_db:/chroma_db
      - ./knowledge_base:/knowledge_base
      - ./rag_kb_updater/_artifacts:/app/_artifacts
      - ./rag_kb_updater/_runs:/app/_runs
    networks:
      - rag-app-net

  rag-api-safe:
    build: ./rag-api-safe
    container_name: rag-api-safe
    env_file:
      - ./rag-api-safe/.env
      - ./rag-api-safe/.env.secrets
    environment:
      - CHROMA_MODE=http
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    ports:
      - "8002:8002"
    depends_on:
      - chroma
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      # нужно для PERSISTENT клиента (но rag-api-safe и rag-kb-updater не смогут работать вместе)
#      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    networks:
      - rag-app-net

  tg-rag-sw-bot-safe:
    build: ../task5/tg-rag-sw-bot-safe
    container_name: tg-rag-sw-bot-safe
    env_file:
      - ../task5/tg-rag-sw-bot-safe/.env
      - ../task5/tg-rag-sw-bot-safe/.env.secrets
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOG_DIR=/app/logs
    ports:
      - "8001:8001"
    depends_on:
      - chroma
      - rag-api-safe
    restart: unless-stopped
    networks:
      - rag-app-net

networks:
  rag-app-net:
    driver: bridge